Latest thing

diff --git a/.github/workflows/auto_publish_release.yml b/.github/workflows/auto_publish_release.yml
--- a/.github/workflows/auto_publish_release.yml
+++ b/.github/workflows/auto_publish_release.yml
@@ -1,4 +1,4 @@
-name: Release stage 2 - auto draft release
+name: Release stage 2 - auto publish
 
 on:
   pull_request:  # types AND paths
@@ -13,13 +13,14 @@ env:
   CHANGELOG_FILE: CHANGES.md
 
 jobs:
-  draft-release:
+  publish:
     if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'prepare-') # Can't use top-level env here
     runs-on: ubuntu-latest
     timeout-minutes: 5
     env:
       PR_BRANCH_PREFIX: 'prepare-'
     steps:
+
     - name: Get the version number
       run: |
         VERSION=$( grep -oP "(?<=${PR_BRANCH_PREFIX}).*" <<< '${{ github.head_ref }}' )
@@ -29,7 +30,25 @@ jobs:
         fi
         echo "::set-env name=VERSION::$VERSION"
 
-    - name: Create draft release
+    - name: Checkout repo
+      uses: actions/checkout@v2.3.1
+      with:
+        ref: ${{ env.MERGE_SHA }}
+
+    - name: Setup Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: '3.x'
+
+    - name: Build
+      run: |
+        python3 setup.py bdist_wheel sdist
+        if ! grep -qF ".whl" <<< "$( ls dist/ )"; then
+          echo "::error:: Wheel file not built"
+          exit 1
+        fi
+
+    - name: Publish GitHub release
       id: create-release
       uses: actions/create-release@v1.1.2
       env:
@@ -41,53 +60,35 @@ jobs:
         body: See [${{ env.CHANGELOG_FILE }}](https://github.com/${{ github.repository }}/blob/master/${{ env.CHANGELOG_FILE }}) for detail. # TODO: preview this info in the PR? Posibly get release number; add description field in the create-release-pr workflow input?
         draft: false
 
+    - name: Publish distribution to PyPI
+      continue-on-error: true
+      id: pypi-publish
+      uses: pypa/gh-action-pypi-publish@v1.3.1
+      with:
+        user: __token__ # uses the API token feature of PyPI - least permissions possible
+        password: ${{ secrets.PYPI_TOKEN }}
+        repository_url: https://test.pypi.org/legacy/
+
+    - name: Log any outputs of PyPI publish
+      run: echo "${{ toJson(steps.pypi-publish.outputs) }}"
+
     - name: Comment on the release PR with the results
       if: always()
-      shell: node {0}
       env:
-        RELEASE_STATUS: ${{ steps.create-release.outcome }}
+        WORKFLOW: ${{ github.workflow }}
+        RUN_NUMBER: ${{ github.run_number }}
+        JOB_STATUS: ${{ job.status }}
         RELEASE_URL: ${{ steps.create-release.outputs.html_url }}
-        ASSIGNEE: ${{ github.event.pull_request.assignees[0].login }}
+        PR_EVENT: ${{ toJson(github.event.pull_request) }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      run: |
-        const {exec} = require('child_process');
-        const {env} = process;
-
-        const bodyText = () => {
-          let icon = '✔️';
-          let note = `Next step for @${env.ASSIGNEE}: [view/edit the release description](${env.RELEASE_URL}) as appropriate`;
-          if (env.RELEASE_STATUS !== 'success') {
-            icon = '❌';
-            note = `[Check the run](${{ github.event.pull_request.html_url }}/checks)`;
-          }
-          const title = `### ${icon} \`${env.RELEASE_STATUS}\`**`;
-          const footer = `Comment created by workflow: \`${{ github.workflow }}\`, run: \`${{ github.run_number }}\``;
-          return `${title}\n\n${note}\n___\n${footer}`;
-        };
-        const payload = JSON.stringify({
-          body: bodyText()
-        });
-        const request = `curl -X POST \
-          ${{ github.event.pull_request.comments_url }} \
-          -H "authorization: Bearer $GITHUB_TOKEN" \
-          -H "content-type: application/json" \
-          --data '${payload}' \
-          --fail --silent --show-error`;
-        exec(request, (err, stdout, stderr) => {
-          if (err) {
-            console.log(`::error:: ${stderr}`);
-            throw err.message;
-          }
-          console.log(`::group::exec ${request.slice(0, 15)}...`);
-          console.log(request, '\n\n', stdout);
-          console.log('::endgroup::');
-        });
+      run: node .github/bin/comment_on_pr.js
 
     - name: Delete the PR branch
+      if: always()
+      continue-on-error: true
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         curl -X DELETE \
           https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${{ github.event.pull_request.head.ref }} \
-          -H "authorization: Bearer $GITHUB_TOKEN" \
-          --fail --silent --show-error
+          -H "authorization: Bearer $GITHUB_TOKEN"
