Latest thing

diff --git a/.github/workflows/create_release_pr.yml b/.github/workflows/create_release_pr.yml
--- a/.github/workflows/create_release_pr.yml
+++ b/.github/workflows/create_release_pr.yml
@@ -24,6 +24,7 @@ jobs:
     runs-on: ubuntu-latest
     timeout-minutes: 5
     steps:
+
     - name: Sanitise workflow inputs # Should be first step
       shell: node {0}
       env:
@@ -83,24 +84,17 @@ jobs:
     - name: Check setup.py version against PyPI.org
       shell: node {0}
       run: |
-        const {exec} = require('child_process');
-        const {env} = process;
         console.log(process.cwd());
-        const request = `curl -X GET https://pypi.org/pypi/${env.PYPI_PACKAGE_NAME}/json`;
-        exec(request, (err, stdout, stderr) => {
-          if (err) {
-            console.log(`::error:: ${stderr}`);
-            throw err.message;
-          }
-          console.log(`::group::exec ${request.slice(0, 15)}...`);
-          console.log(request, '\n\n', JSON.stringify(JSON.parse(stdout), null, 2));
-          console.log('::endgroup::');
+        const {execSync, curlOpts} = require('${{ github.workspace }}/.github/bin/util');
+        const {env} = process;
 
-          const releases = JSON.parse(stdout).releases;
-          if (env.SETUP_PY_VERSION in releases) {
-            throw `${env.SETUP_PY_VERSION} already exists on PyPI.org`;
-          }
-        });
+        const request = `curl -X GET \
+          https://pypi.org/pypi/${env.PYPI_PACKAGE_NAME}/json \
+          ${curlOpts}`
+        const {releases} = JSON.parse(execSync(request));
+        if (env.SETUP_PY_VERSION in releases) {
+          throw `${env.SETUP_PY_VERSION} already exists on PyPI.org`;
+        }
 
     - name: Update "released on" date in changelog
       continue-on-error: true
@@ -118,15 +112,15 @@ jobs:
         git add "$CHANGELOG_FILE"
         echo "::set-env name=CHANGELOG_DATE::$date_now"
 
-    # - name: Test the build
-    #   run: |
-    #     cd $( mktemp -d )
-    #     python3 "${{ github.workspace }}/setup.py" bdist_wheel
-    #     files=$( ls dist/ )
-    #     if ! grep -qF ".whl" <<< "$files"; then
-    #       echo "::error:: No wheel file found"
-    #       exit 1
-    #     fi
+    - name: Test the build
+      continue-on-error: true
+      run: |
+        cd $( mktemp -d )
+        python3 "${{ github.workspace }}/setup.py" bdist_wheel
+        if ! grep -qF ".whl" <<< "$( ls dist/ )"; then
+          echo "::error:: Wheel file not built"
+          exit 1
+        fi
 
     - name: Commit & push
       id: push
@@ -141,10 +135,11 @@ jobs:
         WORKFLOW: ${{ github.workflow }}
         AUTHOR: ${{ github.event.sender.login }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      run: node .github/create_release_pr.js
+      run: node .github/bin/create_release_pr.js
 
     - name: (On fail) Delete failed PR branch on origin, if it was pushed
       if: always() && steps.create-pr.outcome != 'success' && steps.push.outcome == 'success'
+        # Need status check function in if-condition otherwise won't run on fail
       run: |
         backup_sha=$( git rev-parse "origin/${HEAD_REF}" )
         git push -d origin "$HEAD_REF"
