Try new thing

diff --git a/.github/workflows/create_release_pr.yml b/.github/workflows/create_release_pr.yml
--- a/.github/workflows/create_release_pr.yml
+++ b/.github/workflows/create_release_pr.yml
@@ -46,6 +46,11 @@ jobs:
       with:
         python-version: '3.x'
 
+    - name: Install/setup utils
+      run: |
+        pip install -q packaging
+        echo "::add-path::${{ github.workspace }}/.github/bin"
+
     - name: Configure git
       run: |
         git config --global user.name "github-actions[bot]"
@@ -68,81 +73,75 @@ jobs:
 
         git add "$INIT_FILE"
 
-    - name: Check setup.py version is valid
+    - name: Get setup.py version
       # Usually needs to be after updating version in __init__.py
       run: |
-        pip install -q packaging
-
-        export SETUP_PY_VERSION=$( echo "1!$VERSION" ) # $( python setup.py --version )
+        SETUP_PY_VERSION=$( echo "1!$VERSION" ) # $( python setup.py --version )
         echo "::set-env name=SETUP_PY_VERSION::$SETUP_PY_VERSION"
-        python -c "
-        import os
-        import packaging.version
-        packaging.version.Version(os.getenv('SETUP_PY_VERSION'))
-        "
+        # Check version number is valid:
+        cmp_py_versions "$SETUP_PY_VERSION" "$SETUP_PY_VERSION"
 
-    - name: Check setup.py version against PyPI.org
+    - name: Check version doesn't already exist on PyPI.org
       shell: node {0}
       run: |
-        const {execSync, curlOpts} = require('${{ github.workspace }}/.github/bin/util');
+        const {execSync, curlOpts} = require('${{ github.workspace }}/.github/lib/util');
         const {env} = process;
 
         const request = `curl -X GET \
           https://pypi.org/pypi/${env.PYPI_PACKAGE_NAME}/json \
           ${curlOpts}`
         const {releases} = JSON.parse(execSync(request));
-        if (env.SETUP_PY_VERSION in releases) {
-          throw `${env.SETUP_PY_VERSION} already exists on PyPI.org`;
+        for (release in releases) {
+          const diff = execSync(`cmp_py_versions ${release} ${env.SETUP_PY_VERSION}`);
+          if (!diff) {
+            throw `${env.SETUP_PY_VERSION} already exists on PyPI.org`;
+          }
         }
 
-    - name: Update "released on" date in changelog
-      continue-on-error: true
-      run: |
-        pattern="(<span actions:bind='release-date'>).*(<\/span>)"
-        date_now=$( date '+%Y-%m-%d' --utc )
-        replacement="Released $date_now"
-        sed -i -E "0,/${pattern}/s//\1${replacement}\2/" "$CHANGELOG_FILE"  # Only replaces 1st match
+    # - name: Update "released on" date in changelog
+    #   continue-on-error: true
+    #   run: |
+    #     pattern="(<span actions:bind='release-date'>).*(<\/span>)"
+    #     date_now=$( date '+%Y-%m-%d' --utc )
+    #     replacement="Released $date_now"
+    #     sed -i -E "0,/${pattern}/s//\1${replacement}\2/" "$CHANGELOG_FILE"  # Only replaces 1st match
 
-        if [[ -z $(git diff --stat -- "$CHANGELOG_FILE") ]]; then
-          echo "::error:: Couldn't update release date in ${CHANGELOG_FILE}"
-          exit 1
-        fi
+    #     if [[ -z $(git diff --stat -- "$CHANGELOG_FILE") ]]; then
+    #       echo "::error:: Couldn't update release date in ${CHANGELOG_FILE}"
+    #       exit 1
+    #     fi
 
-        git add "$CHANGELOG_FILE"
-        echo "::set-env name=CHANGELOG_DATE::$date_now"
+    #     git add "$CHANGELOG_FILE"
+    #     echo "::set-env name=CHANGELOG_DATE::$date_now"
 
-    - name: Test the build
-      continue-on-error: true
-      run: |
-        cd $( mktemp -d )
-        python3 "${{ github.workspace }}/setup.py" bdist_wheel
-        if ! grep -qF ".whl" <<< "$( ls dist/ )"; then
-          echo "::error:: Wheel file not built"
-          exit 1
-        fi
+    # - name: Test the build
+    #   run: |
+    #     cd $( mktemp -d )
+    #     python3 "${{ github.workspace }}/setup.py" bdist_wheel
 
-    - name: Commit & push
-      id: push
-      run: |
-        git status
-        git commit -m "Prepare release ${VERSION}" -m "Workflow: ${{ github.workflow}}, run: ${{ github.run_number }}"
-        git push origin "$HEAD_REF"
+    # - name: Commit & push
+    #   id: push
+    #   run: |
+    #     git status
+    #     git commit -m "Prepare release ${VERSION}" -m "Workflow: ${{ github.workflow}}, run: ${{ github.run_number }}"
+    #     git push origin "$HEAD_REF"
 
-    - name: Create pull request
-      id: create-pr
-      env:
-        WORKFLOW: ${{ github.workflow }}
-        AUTHOR: ${{ github.event.sender.login }}
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      run: node .github/bin/create_release_pr.js
+    # - name: Create pull request
+    #   id: create-pr
+    #   env:
+    #     WORKFLOW: ${{ github.workflow }}
+    #     RUN_NUMBER: ${{ github.run_number }}
+    #     AUTHOR: ${{ github.event.sender.login }}
+    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+    #   run: node .github/lib/create_release_pr.js
 
-    - name: (On fail) Delete failed PR branch on origin, if it was pushed
-      if: always() && steps.create-pr.outcome != 'success' && steps.push.outcome == 'success'
-        # Need status check function in if-condition otherwise won't run on fail
-      run: |
-        backup_sha=$( git rev-parse "origin/${HEAD_REF}" )
-        git push -d origin "$HEAD_REF"
-        echo "::warning:: Deleted the newly-pushed branch '${HEAD_REF}' because the workflow failed"
-        echo "If you need to recover the branch:"
-        echo "  git fetch origin ${backup_sha}"
-        echo "  git checkout -b ${HEAD_REF} ${backup_sha}"
+    # - name: (On fail) Delete failed PR branch on origin, if it was pushed
+    #   if: always() && steps.create-pr.outcome != 'success' && steps.push.outcome == 'success'
+    #     # Need status check function in if-condition otherwise won't run on fail
+    #   run: |
+    #     backup_sha=$( git rev-parse "origin/${HEAD_REF}" )
+    #     git push -d origin "$HEAD_REF"
+    #     echo "::warning:: Deleted the newly-pushed branch '${HEAD_REF}' because the workflow failed"
+    #     echo "If you need to recover the branch:"
+    #     echo "  git fetch origin ${backup_sha}"
+    #     echo "  git checkout -b ${HEAD_REF} ${backup_sha}"
